### ISSUE TITLE
Whoever wrote this needs serious mental help

### ISSUE THREAD

**Issue by LowSpecCorgi** [bspkrs/DirectionHUD#6]
https://github.com/bspkrs/DirectionHUD/blob/48b4e318b6594674fee7a08c63c041f329361748/src/main/java/bspkrs/directionhud/DirectionHUD.java#L26-L46

**Comment by ImNotStealth** [comment]
I agree this is giving me nightmares and people that have OCD would never do such a thing ! ! !

**Comment by ShadowCube264** [comment]
wtf is that
![withertf](https://user-images.githubusercontent.com/68464043/138295937-ce854324-b3e2-4c01-a4c1-81c82d92c5c5.png)
